# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  name: Default

- task: DotNetCoreCLI@2
  displayName: Build RegexDataGenerator
  inputs:
    command: 'build'
    projects: './Agidens.Aline/Agidens.Aline.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/binaries'
- task: DotNetCoreCLI@2
  displayName: Run unit tests
  inputs:
    command: 'test'
    testRunTitle: 'Unit tests'
    workingDirectory: '.'

